const PDFDocument = require('pdfkit');

const generatePdfReport = (document, res) => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="DocVerify_Report_${document.documentId}.pdf"`);

  doc.pipe(res);

  doc.fontSize(20).fillColor('#1e293b').text('DocVerify AI — Verification Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#64748b').text(`Generated Date: ${new Date().toLocaleString()}`, { align: 'center' });
  doc.moveDown(1.5);

  doc.fontSize(14).fillColor('#0f172a').text('1. Document Metadata', { underline: true });
  doc.fontSize(10).fillColor('#334155')
    .text(`Document ID: ${document.documentId}`)
    .text(`Original File: ${document.originalFileName}`)
    .text(`Type: ${document.documentType} (Confidence: ${document.classificationConfidence}%)`)
    .text(`Status: ${document.status.toUpperCase()}`)
    .text(`Confidence Score: ${document.confidenceScore}%`);
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f172a').text('2. Extracted Data Summary', { underline: true });
  const data = document.extractedData || {};
  doc.fontSize(10).fillColor('#334155')
    .text(`Name: ${data.name || 'N/A'}`)
    .text(`ID/Certificate/Invoice: ${data.certificateId || data.invoiceNumber || data.documentNumber || 'N/A'}`)
    .text(`Issue Date: ${data.issueDate || 'N/A'}`)
    .text(`Expiry Date: ${data.expiryDate || 'N/A'}`);
  doc.moveDown(1);

  doc.fontSize(14).fillColor('#0f172a').text('3. AI Explanation & Findings', { underline: true });
  doc.fontSize(10).fillColor('#334155').text(document.aiExplanation || 'None');
  doc.moveDown(1.5);

  doc.fontSize(8).fillColor('#94a3b8').text('This automated document verification report is generated by DocVerify AI. It acts as an operational validation aid and does not replace official legal certification.', { align: 'center' });

  doc.end();
};

module.exports = { generatePdfReport };